name: "Build"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:  
  build:      
    name: Build & Release 
    runs-on: macos-latest 

    steps:
        #1 Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

        #2 Setup Java
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

        #3 Setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

        #4 Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

        #5 Build APK
      - name: Build APK
        run: flutter build apk

        #8 Build IPA ( IOS Build )
      - name: Build IPA
        run: flutter build ipa --no-codesign

      - name: Compress Archives and IPAs
        run: |
          cd build
          tar -czf ios_build.tar.gz ios

        # Build web
      - name: Build web
        run: flutter build web --base-href /${{ github.event.repository.name }}/
      
      - name: Updage pages artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

        #9 Upload Artifacts
      - name: Upload android Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android_release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload ios Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios_release
          path: build/ios_build.tar.gz
          
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${\{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
